/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import dfa.DfaSimulator;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author silva
 */
public class Program extends javax.swing.JFrame {
    
    
    private final DfaSimulator dfa = new DfaSimulator();
    private File stringsFileDFA;
    private File tableFileDFA;
    
    /**
     * Creates new form Program
     */
    public Program() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        openDFAFile = new javax.swing.JButton();
        openTestFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        openDFAFile.setText("Open DFA Table File");
        openDFAFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDFAFileActionPerformed(evt);
            }
        });

        openTestFile.setText("Open tests file");
        openTestFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTestFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openDFAFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openTestFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(openDFAFile)
                .addGap(34, 34, 34)
                .addComponent(openTestFile)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openDFAFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDFAFileActionPerformed
        // TODO add your handling code here:
        try
        {
            tableFileDFA = dfa.selectFile("Table File DFA");
            if(tableFileDFA != null)
            {
                /*Faz com que o botao nao seja mais clicavel*/
                openDFAFile.setEnabled(false);
                /*Selecionando o arquivo contento a tabela de transicao e imprimindo o arquivo*/
                String[] tableFieldsDFA = dfa.readFile(tableFileDFA);
                dfa.organizeVariables(tableFieldsDFA);
            }
            else
                JOptionPane.showMessageDialog(null, "Não foi possível realizar essa operação no momento,"
                        + " pois a tabela do autômato não foi selecionada."); 
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_openDFAFileActionPerformed

    private void openTestFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTestFileActionPerformed
        // TODO add your handling code here:
        try
        {
            if(tableFileDFA != null)
            {
                stringsFileDFA = dfa.selectFile("Strings File");
                if(stringsFileDFA != null)
                {
                    /*Selecionando o arquivo contento as strings teste e imprimindo o arquivo*/
                    String[] stringsFieldsDFA = dfa.readFile(stringsFileDFA);
                    dfa.organizeInputs(stringsFieldsDFA);
                    dfa.validate();
                }
            }
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_openTestFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Program program = new Program();
                program.setVisible(true);
                program.setLocationRelativeTo(null);
                program.setTitle("DFA Simulator");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton openDFAFile;
    private javax.swing.JButton openTestFile;
    // End of variables declaration//GEN-END:variables
}
